name: Go
on: [push]
jobs:
  validator:
    name: Run Linters and Checkers
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.14
        uses: actions/setup-go@v1
        with:
          go-version: 1.14
        id: go
      - name: Check out code into the Go module directory
        uses: actions/checkout@v1
      - name: Try to use cache
        uses: actions/cache@v1
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |       # Modules from another version are a good start
            ${{ runner.os }}-go-
      - name: Checks validator
        run: |
          make checks-validator
  test:
    name: Run Test Suite
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v1
      - name: Setup UI (node 10)
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - name: install UI dependencies
        run: npm install
        working-directory: ./webui
      - name: Set up Go 1.14
        uses: actions/setup-go@v1
        with:
          go-version: 1.14
        id: go
      - name: Try to use cache
        uses: actions/cache@v1
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |       # Modules from another version are a good start
            ${{ runner.os }}-go-
      - name: Setup statik
        run: |
          go get github.com/rakyll/statik
      - name: Run tests
        run: |
          make test
